application: 9erthalion6
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /music
  static_dir: music
- url: /images
  static_dir: images
- url: /emotions
  static_dir: emotions
- url: /favicon.ico
  static_files: /images/favicon.ico
  upload: /images/favicon.ico 
- url: /yandex_6607f61067d93b44.txt
  static_files: yandex_6607f61067d93b44.txt
  upload: yandex_6607f61067d93b44.txt
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
- url: /raphael
  static_dir: raphael
- url: /.*
  script: index.py

builtins:
- datastore_admin: on
- appstats: on

inbound_services:
- xmpp_message
- mail

error_handlers:
- file: views/error.html