application: 9erthalion6
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /music
  static_dir: music
- url: /raphael
  static_dir: raphael
- url: /.*
  script: index.py
