application: 9erthalion6
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /music
  static_dir: music
- url: /images
  static_dir: images
- url: /emotions
  static_dir: emotions
- url: /favicon.ico
  static_files: /images/favicon.ico
  upload: /images/favicon.ico 
- url: /raphael
  static_dir: raphael
- url: /.*
  script: index.py
